### ISSUE TITLE
blue_hydra_rssi.log has no UUID

### ISSUE THREAD

**Issue by charliebabbitt1988** [ZeroChaos-/blue_hydra#4]
Please consider adding an option in blue_hydra.yml to add the device UUID to the blue_hydra_rssi.log when rssi_log has been set to true.

Hail Blue Hydra!

**Comment by charliebabbitt1988** [comment]
It appears that the necessary edit would be on line 791 in blue_hydra/lib/blue_hydra/runner.rb for the msg variable, but uuid would have to be defined somewhere above.

Can you make a recommendation as to what mod is necessary for a uuid column in blue_hydra_rssi.log?

**Comment by ZeroChaos-** [comment]
the rssi log is an ugly hack.  signal_spitter is a much more useful implementation.  the feature isn't well documented but it opens a port and provides a list of devices with rssi and timestamp.

that said, the database uuid isn't available in either feature, and really isn't available at all outside of the database.  even the ui has a different uuid to track devices than the database uses.  the issue is that the uuid isn't available until database saves, which is the last thing that happens when we see a new device.

this is basically impossible to implement unfortunately.  suggestions welcome
